export interface CountryData {
  name: string;
  cities: string[];
}

export const countriesData: CountryData[] = [
  {
    name: 'India',
    cities: [
      'Mumbai',
      'Delhi',
      'Bangalore',
      'Hyderabad',
      'Chennai',
      'Kolkata',
      'Pune',
      'Ahmedabad',
      'Jaipur',
      'Surat',
      'Lucknow',
      'Kanpur',
      'Nagpur',
      'Indore',
      'Thane',
      'Bhopal',
      'Visakhapatnam',
      'Pimpri-Chinchwad',
      'Patna',
      'Vadodara',
      'Ghaziabad',
      'Ludhiana',
      'Agra',
      'Nashik',
      'Faridabad',
      'Meerut',
      'Rajkot',
      'Kalyan-Dombivali',
      'Vasai-Virar',
      'Varanasi',
      'Srinagar',
      'Aurangabad',
      'Dhanbad',
      'Amritsar',
      'Navi Mumbai',
      'Allahabad',
      'Ranchi',
      'Howrah',
      'Coimbatore',
      'Jabalpur',
      'Gwalior',
      'Vijayawada',
      'Jodhpur',
      'Madurai',
      'Raipur',
      'Kota',
      'Chandigarh',
      'Guwahati',
      'Solapur',
      'Hubli-Dharwad',
    ]
  },
  {
    name: 'USA',
    cities: [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'Austin',
      'Jacksonville',
      'Fort Worth',
      'Columbus',
      'Charlotte',
      'San Francisco',
      'Indianapolis',
      'Seattle',
      'Denver',
      'Washington DC',
      'Boston',
      'El Paso',
      'Nashville',
      'Detroit',
      'Oklahoma City',
      'Portland',
      'Las Vegas',
      'Memphis',
      'Louisville',
      'Baltimore',
      'Milwaukee',
      'Albuquerque',
      'Tucson',
      'Fresno',
      'Mesa',
      'Sacramento',
      'Atlanta',
      'Kansas City',
      'Colorado Springs',
      'Raleigh',
      'Miami',
      'Long Beach',
      'Virginia Beach',
      'Omaha',
      'Oakland',
      'Minneapolis',
      'Tulsa',
      'Tampa',
      'Arlington',
      'New Orleans',
    ]
  },
  {
    name: 'UK',
    cities: [
      'London',
      'Birmingham',
      'Manchester',
      'Leeds',
      'Glasgow',
      'Liverpool',
      'Newcastle',
      'Sheffield',
      'Bristol',
      'Edinburgh',
      'Leicester',
      'Nottingham',
      'Coventry',
      'Bradford',
      'Cardiff',
      'Belfast',
      'Southampton',
      'Plymouth',
      'Reading',
      'Derby',
      'Stoke-on-Trent',
      'Wolverhampton',
      'Brighton',
      'Aberdeen',
      'Swansea',
      'Oxford',
      'Cambridge',
      'York',
      'Bath',
      'Norwich',
    ]
  },
  {
    name: 'Canada',
    cities: [
      'Toronto',
      'Montreal',
      'Vancouver',
      'Calgary',
      'Edmonton',
      'Ottawa',
      'Winnipeg',
      'Quebec City',
      'Hamilton',
      'Kitchener',
      'London',
      'Victoria',
      'Halifax',
      'Oshawa',
      'Windsor',
      'Saskatoon',
      'Regina',
      'Sherbrooke',
      'Barrie',
      'Kelowna',
      'Abbotsford',
      'Sudbury',
      'Kingston',
      'Saguenay',
      'Trois-Rivières',
    ]
  },
  {
    name: 'Australia',
    cities: [
      'Sydney',
      'Melbourne',
      'Brisbane',
      'Perth',
      'Adelaide',
      'Gold Coast',
      'Canberra',
      'Newcastle',
      'Wollongong',
      'Logan City',
      'Geelong',
      'Hobart',
      'Townsville',
      'Cairns',
      'Darwin',
      'Toowoomba',
      'Ballarat',
      'Bendigo',
      'Albury',
      'Launceston',
    ]
  },
  {
    name: 'UAE',
    cities: [
      'Dubai',
      'Abu Dhabi',
      'Sharjah',
      'Ajman',
      'Ras Al Khaimah',
      'Fujairah',
      'Umm Al Quwain',
      'Al Ain',
    ]
  },
  {
    name: 'Singapore',
    cities: [
      'Singapore',
    ]
  },
  {
    name: 'Germany',
    cities: [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
      'Düsseldorf',
      'Dortmund',
      'Essen',
      'Leipzig',
      'Bremen',
      'Dresden',
      'Hanover',
      'Nuremberg',
      'Duisburg',
    ]
  },
  {
    name: 'France',
    cities: [
      'Paris',
      'Marseille',
      'Lyon',
      'Toulouse',
      'Nice',
      'Nantes',
      'Strasbourg',
      'Montpellier',
      'Bordeaux',
      'Lille',
      'Rennes',
      'Reims',
      'Le Havre',
      'Saint-Étienne',
      'Toulon',
    ]
  },
  {
    name: 'Netherlands',
    cities: [
      'Amsterdam',
      'Rotterdam',
      'The Hague',
      'Utrecht',
      'Eindhoven',
      'Tilburg',
      'Groningen',
      'Almere',
      'Breda',
      'Nijmegen',
    ]
  },
  {
    name: 'New Zealand',
    cities: [
      'Auckland',
      'Wellington',
      'Christchurch',
      'Hamilton',
      'Tauranga',
      'Napier-Hastings',
      'Dunedin',
      'Palmerston North',
      'Nelson',
      'Rotorua',
    ]
  },
  {
    name: 'Ireland',
    cities: [
      'Dublin',
      'Cork',
      'Limerick',
      'Galway',
      'Waterford',
      'Drogheda',
      'Dundalk',
      'Swords',
      'Bray',
      'Navan',
    ]
  },
];
